### ISSUE TITLE
Unable to use a parameter named `user_id`

### ISSUE THREAD

**Issue by richrd** [forbesmyester/esqlate#9]
Hi! Really neat project! I was trying this out and made a simple definition for looking up users by their id. Regardless of what user_id I supplied it always returned the user with ID 999. This seems to be causing it but I have no idea what that's for: https://github.com/forbesmyester/esqlate-server/blob/master/src/server.ts#L171

I can easily work around this by changing the parameter name but this did surprise me a bit :slightly_smiling_face:

**Comment by forbesmyester** [comment]
Hi, thanks for your interest, people finding stupid bugs like this warms my heart because I can see that people are actually using it!

This code currently serves no purpose. It's left over really early code from when I was thinking about variables coming from different places, maybe as environmental variables or something else.

I'm in the middle of working on #4 and will come back to this over the next week or so if you could work around it for the time being that'd be great :-)

**Comment by richrd** [comment]
This was a rather fun bug to find, a genuine WTF moment :smile: Really nice hear #4 getting some attention. I can easily work around this for now.
